name: learn-github-actions
on: [push]
jobs:
    checks-bats-version:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12, 14, 16]
        steps:
            - uses: action/setup-node@v3
              with:
                  node-version: ${{ matrix.node }}
